### ISSUE TITLE
Exclude routes from checking

### ISSUE THREAD

**Issue by greal** [jrmadsen67/laravel-route-coverage-test#6]
Good day!

I just wanted to suggest an idea for finalizing the package. For example, in order to be able to exclude any routes or groups of routes from the check.

**Comment by johnnymast** [comment]
This is actually a good addition. How would you do this, add a config file? You can contribute if you wish. I have updated this package 11 days ago to make Laravel auto-discover the files and it was merged in. I think your addition could be merged in as well.

**Comment by ferhatbostanci** [comment]
Hi @greal, added exclude route in PR https://github.com/jrmadsen67/laravel-route-coverage-test/pull/9.

**Comment by jrmadsen67** [comment]
@ferhatbostanci Thanks & sorry for missing this

I looked at your code, but I don't think that it actually *reads* from anywhere which routes to leave out. Can you either explain that if I've missed something, or add the bit to read from the config file?

TIA!

**Comment by othyn** [comment]
Submitted a PR for v2.0 of this package that includes this feature, see #12

**Comment by jrmadsen67** [comment]
fixed with other big update
